version: 2
sources:
    - name: snowflake_data
      database: "{{('dbt_db')}}"
      schema: dev
      tables:
        - name: RAW_LINEITEM
          columns:
            - name: l_orderkey
              tests:
                - not_null
            - name: l_quantity
              tests:
                - not_null
            - name: l_linenumber
              tests:
                - not_null  
        - name: RAW_NATION
          columns:
            - name: n_nationkey
              tests:
                - unique
                - not_null
            - name: n_name
              tests:
                - not_null
        - name: RAW_ORDERS
          columns:
          - name: o_orderkey
          tests:
            - unique
            - not_null

        - name: RAW_CUSTOMER 
          columns:
           - name: c_custkey
             tests:
              - unique
              - not_null
           - name: c_name
             tests:
             - not_null
      